### ISSUE TITLE
自动回复规则提交更新后，update_time字段不会更新

### ISSUE THREAD

**Issue by nichujie** [niefy/wx-manage#27]
* 前端提交自动回复规则的更新表单后，update_time字段不会更新。
* 点“修改”后再创建新规则，新规则的update_time不对

原理：在点开“修改”查看某条规则的具体内容时，那条信息的update_time字段被赋给了dataForm，导致后续的修改/新增操作都会带上这条信息的update_time发送给后端。后端接收到了update_time字段，则不会自动更新该字段（而是使用接收到的update_time来更新）。

具体修复：https://github.com/nichujie/wx-manage/commit/4aae8775b3090deddab9375db71eb69b5fb9a3a6

**Comment by niefy** [comment]
已采纳
