### ISSUE TITLE
被遮罩层遮住无法点击页面，只能刷新

### ISSUE THREAD

**Issue by zhishiguai** [niefy/wx-manage#31]
自动回复规则点击新增，然后选择图片消息，从素材库选择跳出弹窗，点击新增，会出来上传图片页面这个页面就被遮罩层挡住了
![image](https://user-images.githubusercontent.com/39476487/89486929-bce02200-d7d6-11ea-820f-1e30f963ee40.png)

**Comment by niefy** [comment]
选择模式下已隐藏新增按钮，请更新代码后体验
