### ISSUE TITLE
添加文章后不能正常显示

### ISSUE THREAD

**Issue by jiuzhuaxiong** [niefy/wx-manage#35]
场景：
      内容系统->添加文章-》新增加文章-》然后保存-》点击文章标题，无法显示或者预览，生成的链接无法使用

**Comment by niefy** [comment]
文章是为了给用户端用的，管理后台需要查看直接编辑即可，比如再wx-client中可以加载。
如果你生产环境wx-manage和wx-client都部署了就可以查看
