### ISSUE TITLE
此不是bug,仅请教

### ISSUE THREAD

**Issue by matthuo333** [niefy/wx-manage#42]
大神，你好，
看项目中的“自动回复”功能，是基于微信的客服消息模块。查了下，貌似没有多级关键字的自动回复。
这里的多级是指，用户通过自动回复消息内容，按照“指引”（超链，但不是外链）转到最终的内容。
这个功能有可能实现么？

**Comment by niefy** [comment]
建议了解下菜单消息
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html#7

**Comment by matthuo333** [comment]
菜单消息有两个限制，一个仅适用服务号，另个貌似不能在服务端收到xml后，不能再次发消息给客户端
